version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./docker-redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
